Repository weaviate/Verba, pull requests merged in 2023-09, with the labels that each got.

#2 Add OpenAI Example data
  .gitignore
  CHANGELOG.md
  README.md
  data/openai/openai-api-documentation.txt
Labels: documentation

#3 Only stop when using embedded option
  goldenverba/ingestion/import_data.py
  goldenverba/ingestion/init_cache.py
  goldenverba/ingestion/init_schema.py
  goldenverba/ingestion/init_suggestion.py
Labels: bug

#14 Improve Docker build, compose and connection check
  Dockerfile
  README.md
  docker-compose.yml
  goldenverba/ingestion/cli.py
  goldenverba/ingestion/init_cache.py
  goldenverba/ingestion/init_schema.py
  goldenverba/ingestion/init_suggestion.py
  goldenverba/ingestion/preprocess.py
  goldenverba/server/api.py
Labels: documentation, enhancement
